apiVersion: v1
kind: Secret
metadata:
  name: s3creds
  annotations:
    serving.kserve.io/s3-endpoint: s3.ap-south-1.amazonaws.com
    serving.kserve.io/s3-usehttps: "1"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "<your_aws_access_key_id>"
  AWS_SECRET_ACCESS_KEY: "<your_aws_secret_access_key>"
  AWS_DEFAULT_REGION: "ap-south-1"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-sa
secrets:
  - name: s3creds